"""Qt-free calibration profile control use cases."""
from __future__ import annotations
from pathlib import Path
from typing import Protocol
from ..domain import CalibrationApplicability, CalibrationImportPreview, CalibrationProfile, CalibrationSignature

class CalibrationControlPort(Protocol):
    def list_profiles(self) -> tuple[CalibrationProfile, ...]: ...
    def set_current_settings(self, settings: CalibrationSignature) -> CalibrationSignature: ...
    def applicability(self, profile: CalibrationProfile, current: CalibrationSignature | None = None) -> CalibrationApplicability: ...
    def preview_csv_path(self, path: Path, profile_id: str, profile_version: int) -> CalibrationImportPreview: ...
    def preview_csv(self, data: str, profile_id: str = "imported", profile_version: int = 1) -> CalibrationImportPreview: ...
    def finalize_preview(self, preview: CalibrationImportPreview, signature: CalibrationSignature | None = None) -> CalibrationProfile: ...
    def select_active_profile(self, profile: CalibrationProfile, *, expert_override: bool = False) -> CalibrationApplicability: ...
    def clear_active_profile(self) -> None: ...

class CalibrationControlUseCases(Protocol):
    def list_profiles(self) -> tuple[CalibrationProfile, ...]: ...
    def set_current_settings(self, settings: CalibrationSignature) -> CalibrationSignature: ...
    def applicability(self, profile: CalibrationProfile) -> CalibrationApplicability: ...
    def preview_path(self, path: Path, profile_id: str, profile_version: int) -> CalibrationImportPreview: ...
    def preview_text(self, data: str, profile_id: str, profile_version: int) -> CalibrationImportPreview: ...
    def finalize_preview(self, preview: CalibrationImportPreview, signature: CalibrationSignature | None = None) -> tuple[CalibrationProfile, tuple[CalibrationProfile, ...]]: ...
    def activate(self, profile: CalibrationProfile, *, expert_override: bool = False) -> CalibrationApplicability: ...
    def clear_active(self) -> None: ...

class CalibrationControlApplicationService:
    def __init__(self, port: CalibrationControlPort) -> None: self._port = port
    def list_profiles(self) -> tuple[CalibrationProfile, ...]: return self._port.list_profiles()
    def set_current_settings(self, settings: CalibrationSignature) -> CalibrationSignature: return self._port.set_current_settings(settings)
    def applicability(self, profile: CalibrationProfile) -> CalibrationApplicability: return self._port.applicability(profile)
    def preview_path(self, path: Path, profile_id: str, profile_version: int) -> CalibrationImportPreview: return self._port.preview_csv_path(path, profile_id, profile_version)
    def preview_text(self, data: str, profile_id: str, profile_version: int) -> CalibrationImportPreview: return self._port.preview_csv(data, profile_id, profile_version)
    def finalize_preview(self, preview: CalibrationImportPreview, signature: CalibrationSignature | None = None) -> tuple[CalibrationProfile, tuple[CalibrationProfile, ...]]:
        profile = self._port.finalize_preview(preview, signature)
        return profile, self._port.list_profiles()
    def activate(self, profile: CalibrationProfile, *, expert_override: bool = False) -> CalibrationApplicability: return self._port.select_active_profile(profile, expert_override=expert_override)
    def clear_active(self) -> None: self._port.clear_active_profile()

__all__ = ["CalibrationControlApplicationService", "CalibrationControlPort", "CalibrationControlUseCases"]
