"""Interfaces for SDR services rendered by the AppShell.

These are Qt-free contracts: the presenter/worker side is threaded, exposes
polling-style accessors and never calls into PySide6.  The widget side can be
any ``QWidget`` registered by the workspace factory.
"""

from __future__ import annotations

from concurrent.futures import Future
from pathlib import Path
import threading
from typing import Any, Callable, Protocol

from ..domain import (
    CalibrationApplicability,
    CalibrationImportPreview,
    CalibrationProfile,
    CalibrationSignature,
    DiagnosticsSnapshot,
    RecordingHealth,
    RecordedFrame,
    RecordingIndex,
    RecordingOptions,
    RecordingResult,
    ReplayKind,
    ReplayPosition,
    ReprocessResult,
    SelfTestResult,
    SupportBundleOptions,
    SupportBundleResult,
)


class LiveSdrService(Protocol):
    """Bounded live SDR session lifecycle, metrics polling and
    cancellation.  No DFL concepts here."""

    def open_live(self, config: Any) -> None: ...
    def close_live(self) -> None: ...
    def poll_frames(self) -> list[Any]: ...
    def poll_live_metrics(self, timeout_s: float) -> Any: ...
    def is_running(self) -> bool: ...
    def stop_and_wait(self, timeout_s: float) -> None: ...
    def discover_devices(self) -> tuple[Any, ...]: ...
    def discover_startup_devices(self) -> tuple[Any, ...]: ...
    def select_device(self, device_id: str) -> Any: ...
    def select_manual_uri(self, uri: str) -> Any: ...
    def apply_configuration(self, requested: Any) -> Any: ...
    def start(self) -> Any: ...
    def stop(self) -> Any: ...
    def latest_snapshot(self) -> Any: ...


class SweepSdrService(Protocol):
    """Plan before run.  Results include quality/seam, never fabricate."""

    def plan(self, config: Any) -> Any: ...
    def execute(self, config: Any, progress: Callable[[Any], None]) -> Any: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...
    def export_result(self, result: Any, output_path: Any) -> Any: ...


class CalibrationSdrService(Protocol):
    """Calibration profiles browse/compare/finalize; checks applicability."""

    def list_profiles(self) -> tuple[CalibrationProfile, ...]: ...
    def set_current_settings(self, settings: CalibrationSignature) -> CalibrationSignature: ...
    def applicability(self, profile: CalibrationProfile, current: CalibrationSignature | None = None) -> CalibrationApplicability: ...
    def preview_csv_path(self, path: Path, profile_id: str, profile_version: int) -> CalibrationImportPreview: ...
    def preview_csv(self, data: str, profile_id: str = "imported", profile_version: int = 1) -> CalibrationImportPreview: ...
    def finalize_preview(self, preview: CalibrationImportPreview, signature: CalibrationSignature | None = None) -> CalibrationProfile: ...
    def select_active_profile(self, profile: CalibrationProfile, *, expert_override: bool = False) -> CalibrationApplicability: ...
    def clear_active_profile(self) -> None: ...


class RecordingSdrService(Protocol):
    """Bounded IQ/Spectrum recording with recovery and replay."""

    def start(self, options: RecordingOptions) -> None: ...
    def start_now(self, options: RecordingOptions) -> None: ...
    def stop(self, timeout_s: float = 5.0) -> RecordingResult: ...
    def health(self) -> RecordingHealth: ...
    def recover_partial(self, uri: Any) -> Any: ...
    def close(self) -> None: ...


class ReplaySdrService(Protocol):
    """Indexed replay and cancellable reprocess infrastructure."""

    @property
    def position(self) -> ReplayPosition: ...

    def open(self, uri: str | Path, *, kind: ReplayKind = ReplayKind.ALL) -> RecordingIndex: ...
    def seek(self, fraction: float) -> ReplayPosition: ...
    def set_speed(self, speed: float) -> float: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def read_next(self) -> RecordedFrame | None: ...
    def reprocess_iq(self, uri: str | Path, backend: str) -> Future[ReprocessResult]: ...
    def cancel_reprocess(self) -> None: ...
    def close(self) -> None: ...


class DiagnosticsTaskSupervisor(Protocol):
    def submit(self, operation: Callable[[threading.Event], Any]) -> Future[Any]: ...
    def cancel(self) -> None: ...


class DiagnosticsSdrService(Protocol):  # pragma: no cover - interface only
    """Platform/native introspection, safe self tests, anonymized bundle."""

    @property
    def supervisor(self) -> DiagnosticsTaskSupervisor: ...

    def collect_platform(self) -> dict[str, Any]: ...
    def collect_snapshot(self) -> DiagnosticsSnapshot: ...
    def run_self_tests(self, cancel_event: threading.Event | None = None) -> list[SelfTestResult]: ...
    def run_controlled_rx_test(self, confirmed: bool, cancel_event: threading.Event | None = None) -> SelfTestResult: ...
    def run_offline_validation(self, **kwargs: Any) -> Any: ...
    def export_support_bundle(self, output_dir: Any, options: SupportBundleOptions | None = None) -> SupportBundleResult: ...
    def report_error(self, summary: str, reason: str, recommendation: str, technical_detail: str, source: str = "application") -> Any: ...
    def shutdown(self) -> None: ...


__all__ = [
    "CalibrationSdrService",
    "DiagnosticsSdrService",
    "DiagnosticsTaskSupervisor",
    "LiveSdrService",
    "RecordingSdrService",
    "ReplaySdrService",
    "SweepSdrService",
]
