"""Interfaces for SDR services rendered by the AppShell.

These are Qt-free contracts: the presenter/worker side is threaded, exposes
polling-style accessors and never calls into PySide6.  The widget side can be
any ``QWidget`` registered by the workspace factory.
"""

from __future__ import annotations

from typing import Any, Callable, Protocol


class LiveSdrService(Protocol):
    """Bounded live SDR session lifecycle, metrics polling and
    cancellation.  No DFL concepts here."""

    def open_live(self, config: Any) -> None: ...
    def close_live(self) -> None: ...
    def poll_frames(self) -> list[Any]: ...
    def poll_live_metrics(self, timeout_s: float) -> Any: ...
    def is_running(self) -> bool: ...
    def stop_and_wait(self, timeout_s: float) -> None: ...


class SweepSdrService(Protocol):
    """Plan before run.  Results include quality/seam, never fabricate."""

    def plan(self, config: Any) -> Any: ...
    def execute(self, config: Any, progress: Callable[[Any], None]) -> Any: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...


class CalibrationSdrService(Protocol):
    """Calibration profiles browse/compare/finalize; checks applicability."""

    def list_profiles(self) -> tuple[Any, ...]: ...
    def compare_applicability(self, profile: Any, current: Any) -> bool: ...
    def finalize_profile(self, profile: Any) -> Any: ...
    def preview_csv(self, data: str) -> Any: ...


class RecordingSdrService(Protocol):
    """Bounded IQ/Spectrum recording with recovery and replay."""

    def start(self, options: Any) -> None: ...
    def stop(self) -> Any: ...
    def health(self) -> Any: ...
    def recover_partial(self, uri: Any) -> Any: ...
    def open_replay(self, uri: Any, *, kind: Any) -> Any: ...
    def seek(self, fraction: float) -> None: ...
    def reprocess_iq(self, uri: Any, backend: Any) -> Any: ...


class DiagnosticsSdrService(Protocol):  # pragma: no cover - interface only
    """Platform/native introspection, safe self tests, anonymized bundle."""

    def collect_platform(self) -> dict[str, Any]: ...
    def run_self_tests(self) -> list[str]: ...
    def run_offline_validation(self, **kwargs: Any) -> Any: ...
    def export_support_bundle(self, output_dir: Any) -> Any: ...


__all__ = [
    "CalibrationSdrService",
    "DiagnosticsSdrService",
    "LiveSdrService",
    "RecordingSdrService",
    "SweepSdrService",
]
