function(sdr_core_apply_sanitizers target)
    if(NOT SDR_CORE_ENABLE_SANITIZERS)
        return()
    endif()
    if(MSVC)
        message(FATAL_ERROR "SDR_CORE_ENABLE_SANITIZERS is not supported by the P01 MSVC preset")
    endif()
    target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -fsanitize=address,undefined)
endfunction()
